language: go
sudo: false
go:
  - 1.8
  - 1.9
  - master 

matrix:
  allow_failures:
    - go: master 

install:
  - make deps

script:
  - make

before_deploy:
  - make dist

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file_glob: true
  file: 'dist/*.{tar.gz,zip}'
  skip_cleanup: true
  on:
    branch: release
    tags: true
    go: 1.9