language: go
sudo: false
go:
  - 1.8
  - 1.9
  - master 

matrix:
  allow_failures:
    - go: master 

install:
  - go get github.com/mattn/go-scan
  - go get github.com/olekukonko/tablewriter 
  - go get golang.org/x/crypto/ssh/terminal
  - go get github.com/stretchr/testify/assert

script:
  - go test -cover
